development:
  sessions:
    default:
      database: test_minch_dev
      hosts: 
        - localhost:27017

test:
  sessions:
    default:
      database: test_minch_test
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: <%= ENV["MONGOID_DATABASE"] %>
      username: <%= ENV["MONGOID_USERNAME"] %>
      password: <%= ENV["MONGOID_PASSWORD"] %>
      hosts:
        - "<%= ENV["MONGOID_HOST"] %>:<%= ENV["MONGOID_PORT"] %>"
